worker.node1.port=8009
worker.node1.host=192.168.48.185
worker.node1.type=ajp13
worker.node1.ping_mode=A
worker.node1.lbfactor=1

worker.node2.port=8209
worker.node2.host=192.168.48.185
worker.node2.type=ajp13
worker.node2.ping_mode=A
worker.node2.lbfactor=1


worker.loadbalancer.type=lb
worker.loadbalancer.balance_workers=node1,node2
worker.loadbalancer.sticky_session=False
worker.list=loadbalancer
